"""Launch Blender background tasks with controlled environment and logging.

This module selects an appropriate Blender binary, prepares a temporary
datafile for the background script, spawns Blender with flags, streams output,
and cleans up afterwards.
"""

from __future__ import annotations

import json
import os
import re
import shutil
import stat
import subprocess
import sys
import tempfile
import threading
from collections import deque
from collections.abc import Callable
from dataclasses import dataclass
from functools import cache
from typing import Any

from . import config, log, paths, read_header, utils

logger = log.create_logger(__name__)

# Verbosity constants
VERBOSITY_STDERR: int = 1
VERBOSITY_ALL: int = 2
STREAM_TAIL_LINE_LIMIT: int = 200

# Stderr patterns that are harmless warnings rather than real errors.
# Lines matching any of these are downgraded from ERROR to WARNING.
_STDERR_WARN_PATTERNS: tuple[str, ...] = ()
_STDERR_DEBUG_PATTERNS: tuple[str, ...] = ("DeprecationWarning:",)

# Stdout substrings for noisy, harmless Blender messages (e.g. the glTF
# exporter's animation-baking warnings). Matching lines are demoted from INFO
# to DEBUG so they don't clutter normal output.
# These generated by hundreds, so this also speeds up the export.
_STDOUT_IGNORE_PATTERNS: tuple[str, ...] = (
    "Baking animation because of unsupported constraints",
    "Baking animation because there are keyframes with different interpolation",
    "Invalid animation fcurve data",
)

# Release-cycle markers Blender prints on the first line of `blender --version`
# (e.g. "Blender 4.6.0 Alpha"). Stable releases print no such suffix. Used to
# avoid picking pre-release builds when selecting the NEWEST Blender.
_PRERELEASE_MARKERS: tuple[str, ...] = ("alpha", "beta", "candidate")
# Max seconds to wait for `blender --version` when probing a build's cycle.
_VERSION_PROBE_TIMEOUT: int = 30


def get_blender_version_from_blend(blend_file_path: str) -> str:
    """Extract Blender version from a .blend file header (2.8+ heuristic).

    Returns 'major.minor' as a string. Falls back to '2.93' if not detected.
    """
    # we have slightly more advanced method in read_header, which supports compressed blends
    version_data = None
    try:
        version_data = read_header.detect_blender_version(blend_file_path)
    except Exception as exc:  # noqa: BLE001
        # Not fatal: the byte-level fallback below still recovers a version.
        logger.warning("Header version reader failed (%s); using byte fallback.", exc)

    if version_data and version_data["version"]:
        return version_data["version"]

    with open(blend_file_path, "rb") as blend_file:
        header = blend_file.read(24)
        if header[0:7] == b"BLENDER":
            version_bytes = header[9:12]
            version = (chr(version_bytes[0]), chr(version_bytes[2]))
        elif header[12:19] == b"BLENDER":
            version_bytes = header[21:24]
            version = (chr(version_bytes[0]), chr(version_bytes[2]))
        else:
            version = ("2", "93")
        ver_str = ".".join(version)
        logger.debug("Blend header reported version %s", ver_str)
        return ver_str


def _binary_path_for(blenders_path: str, dir_name: str) -> str:
    """Build the OS-specific Blender executable path for a version directory."""
    if sys.platform == "darwin":  # macOS
        return os.path.join(blenders_path, dir_name, "Contents", "MacOS", "Blender")
    ext = ".exe" if sys.platform == "win32" else ""
    return os.path.join(blenders_path, dir_name, f"blender{ext}")


def _dirname_is_prerelease(dir_name: str) -> bool | None:
    """Infer release cycle from a version directory/tag name.

    We control the Blender container builder, so the cycle can be encoded in the
    tag (e.g. 'blender-5.2-alpha' -> dir '5.2-alpha'). Reading it from the name
    avoids spawning Blender just to learn its cycle.

    Returns:
        True  if the name carries a pre-release marker (alpha/beta/rc),
        False if it carries an explicit stable marker (stable/release/lts),
        None  if the name says nothing about the cycle (caller should probe).
    """
    # Tokenize on non-alphanumeric separators so 'rc' doesn't match inside words.
    tokens = {tok for tok in re.split(r"[^a-z0-9]+", dir_name.lower()) if tok}
    if tokens & {*_PRERELEASE_MARKERS, "rc"}:
        return True
    if tokens & {"stable", "release", "lts"}:
        return False
    return None


@cache
def _probe_is_prerelease(binary: str) -> bool:
    """Return True if `blender --version` reports an alpha/beta/RC build.

    Probes the binary at runtime so we never have to change how the version
    directories are built or named. The result is cached per binary path since
    probing spawns Blender and is slow. On any failure (missing binary, timeout,
    unexpected output) we conservatively return False so selection still works.
    """
    try:
        result = subprocess.run(
            [binary, "--version"],
            capture_output=True,
            text=True,
            timeout=_VERSION_PROBE_TIMEOUT,
            check=False,
        )
    except (OSError, subprocess.SubprocessError) as exc:
        logger.warning("Could not probe Blender version for %s: %s", binary, exc)
        return False

    # The release cycle is on the first "Blender X.Y.Z <Cycle>" line.
    first_line = next((ln for ln in result.stdout.splitlines() if ln.strip()), "")
    lowered = first_line.lower()
    is_prerelease = any(marker in lowered for marker in _PRERELEASE_MARKERS)
    if is_prerelease:
        logger.debug("Detected pre-release Blender build: %s", first_line.strip())
    return is_prerelease


def _is_prerelease_build(dir_name: str, binary: str) -> bool:
    """Decide whether a Blender build is a pre-release.

    Prefers the cheap name-based marker (the builder can tag the cycle); only
    falls back to the slow `blender --version` probe when the name is silent.
    """
    from_name = _dirname_is_prerelease(dir_name)
    if from_name is not None:
        return from_name
    return _probe_is_prerelease(binary)


def _select_newest_stable(blenders: list[tuple[float, str]], blenders_path: str) -> tuple[float, str]:
    """Pick the newest non-pre-release Blender, falling back to the newest overall.

    Iterates installed versions from newest to oldest and returns the first one
    that is a stable release. The cycle is read from the directory/tag name when
    present, otherwise probed via `blender --version`. If every build is a
    pre-release (or none can be classified), returns the newest version so
    behavior degrades gracefully instead of failing.
    """
    for candidate in sorted(blenders, key=lambda x: x[0], reverse=True):
        binary = _binary_path_for(blenders_path, candidate[1])
        if not _is_prerelease_build(candidate[1], binary):
            return candidate
        logger.info("Skipping pre-release Blender %s for NEWEST selection", candidate[1])
    logger.warning("No stable Blender build found; falling back to newest available.")
    return max(blenders, key=lambda x: x[0])


def get_blender_binary(asset_data: dict[str, Any], file_path: str = "", binary_type: str = "CLOSEST") -> str:
    """Pick the appropriate Blender binary based on asset metadata and policy.

    Args:
        asset_data: Asset metadata; expects 'sourceAppVersion' and 'assetType'.
        file_path: Path to a .blend file to derive version from if present.
        binary_type: 'CLOSEST' or 'NEWEST'. CLOSEST uses nearest to asset version.

    Returns:
        Absolute path to the chosen Blender executable.

    Raises:
        RuntimeError: If no binaries are found or the selected binary doesn't exist.
    """
    blenders_path = config.BLENDERS_PATH

    # Get available blender versions
    blenders = utils.get_all_blender_versions(blenders_path)

    if len(blenders) == 0:
        raise RuntimeError(f"No valid Blender versions found in {blenders_path}")

    if binary_type == "CLOSEST":
        # get asset's blender upload version
        source_ver = str(asset_data.get("sourceAppVersion", "0.0"))
        asset_blender_version = utils.version_to_float(source_ver)

        logger.debug("Asset Blender version (metadata): %s -> %s", source_ver, asset_blender_version)

        asset_blender_version_from_blend = get_blender_version_from_blend(file_path) if file_path else "0.0"
        logger.debug("Asset Blender version (from blend): %s", asset_blender_version_from_blend)

        asset_blender_version_from_blend_f = utils.version_to_float(asset_blender_version_from_blend)
        asset_blender_version = max(asset_blender_version, asset_blender_version_from_blend_f)
        logger.debug("Asset Blender version (picked): %s", asset_blender_version)

        # Never pick a Blender newer than the source: re-saving an old .blend
        # with a newer Blender would silently upgrade (and corrupt) the asset.
        # Choose the highest installed version that is <= the asset version, and
        # only fall back to the oldest available when the asset predates them all.
        not_newer = [b for b in blenders if b[0] <= asset_blender_version]
        blender_target = max(not_newer, key=lambda x: x[0]) if not_newer else min(blenders, key=lambda x: x[0])
    if binary_type == "NEWEST":
        blender_target = _select_newest_stable(blenders, blenders_path)

    # use latest blender version for hdrs (the .blend is a fresh template, so a
    # newer Blender does not upgrade any user-authored file)
    if str(asset_data.get("assetType", "")).lower() == "hdr":
        blender_target = _select_newest_stable(blenders, blenders_path)

    logger.debug("Selected Blender target: %s", blender_target)

    binary = _binary_path_for(blenders_path, blender_target[1])

    logger.info("Using Blender binary: %s", binary)
    if not os.path.exists(binary):
        raise RuntimeError(f"Blender binary not found at {binary}")

    return binary


def get_process_flags() -> int:
    """Get OS-specific priority flags so subprocess runs at lower priority."""
    below_normal_priority_class = 0x00004000
    return below_normal_priority_class if sys.platform == "win32" else 0


def _reader_thread(pipe: Any, func: Callable[[str], None]) -> None:
    """Read a pipe line-by-line and pass decoded text to a callback."""
    for line in iter(pipe.readline, b""):
        func(line.decode(errors="replace").strip())
    pipe.close()


def _collecting_callback(
    callback: Callable[[str], None],
    collector: deque[str],
) -> Callable[[str], None]:
    """Wrap a pipe callback so streamed lines are stored for later inspection."""

    def wrapper(line: str) -> None:
        collector.append(line)
        callback(line)

    return wrapper


def _log_stream_tail(stream_name: str, lines: deque[str]) -> None:
    """Log the captured trailing lines of a Blender stream for easier debugging."""
    if not lines:
        logger.error("%s stream produced no output before failure.", stream_name)
        return
    joined = "\n".join(lines)
    logger.error("Captured %s tail (%d lines):\n%s", stream_name, len(lines), joined)


def _select_binary_path(
    binary_path: str,
    asset_data: dict[str, Any],
    *,
    asset_file_path: str,
    binary_type: str,
) -> str:
    """Choose Blender binary path either from input or by detection."""
    if binary_path:
        logger.info("Send_to_BG: using predefined Blender binary path: %s", binary_path)
        return binary_path
    try:
        detected = get_blender_binary(asset_data, file_path=asset_file_path, binary_type=binary_type)
    except RuntimeError:
        # Source-version auto-selection could not find a usable Blender (e.g.
        # BLENDERS_PATH is unset or empty in this environment). Fall back to the
        # single configured BLENDER_PATH rather than failing the whole job.
        if config.BLENDER_PATH:
            logger.warning(
                "Send_to_BG: source-version selection failed, falling back to BLENDER_PATH: %s",
                config.BLENDER_PATH,
            )
            return config.BLENDER_PATH
        raise
    logger.info("Send_to_BG: using detected Blender binary path: %s", detected)
    return detected


def _ensure_temp_folder(temp_folder: str) -> tuple[str, bool]:
    """Ensure a temporary folder exists; return the path and ownership flag."""
    if temp_folder:
        return temp_folder, False
    created = tempfile.mkdtemp()
    return created, True


def _write_datafile(
    temp_folder: str,
    payload: DataPayload,
) -> str:
    """Write the JSON datafile used by the background script and return its path."""
    data = {
        "file_path": payload.file_path,
        "result_filepath": payload.result_filepath,
        "result_folder": payload.result_folder,
        "asset_data": payload.asset_data,
        "api_key": payload.api_key,
        "temp_folder": temp_folder,
        "target_format": payload.target_format,
    }
    datafile = os.path.join(temp_folder, "resdata.json").replace("\\", "\\\\")
    with open(datafile, "w", encoding="utf-8") as stream:
        json.dump(data, stream, ensure_ascii=False, indent=4)
    return datafile


def _resolve_template(template_file_path: str, asset_file_path: str) -> str:
    """Return the template path, defaulting to the asset file if not provided."""
    if template_file_path:
        return template_file_path
    return asset_file_path


def _build_command(
    binary_path: str,
    template_file_path: str,
    script: str,
    datafile: str,
    addons: str,
) -> list[str]:
    """Construct the Blender CLI command list with optional addons."""
    command: list[str] = [
        binary_path,
        "--background",
        "--factory-startup",
        "-noaudio",
        template_file_path,
        "--python",
        os.path.join(paths.BG_SCRIPTS_PATH, script),
        "--",
        datafile,
    ]
    if addons:
        command.insert(3, "--addons")
        command.insert(4, addons)
    return command


class _StderrCallback:
    """Stateful stderr callback that downgrades known multi-line warnings.

    Python warnings (e.g. DeprecationWarning) emit two lines: the warning
    message followed by the offending source line. This callback tracks
    whether the previous line matched a known harmless pattern so the
    continuation line is also downgraded from ERROR to WARNING or DEBUG.
    """

    def __init__(self) -> None:
        self._w_continuation = False
        self._d_continuation = False

    def __call__(self, line: str) -> None:
        for pattern in _STDERR_WARN_PATTERNS:
            if pattern in line:
                logger.warning("STDERR: %s", line)
                self._w_continuation = True
                return
        if self._w_continuation:
            logger.warning("STDERR: %s", line)
            self._w_continuation = False
            return
        for pattern in _STDERR_DEBUG_PATTERNS:
            if pattern in line:
                logger.debug("STDERR: %s", line)
                self._d_continuation = True
                return
        if self._d_continuation:
            logger.debug("STDERR: %s", line)
            self._d_continuation = False
            return
        logger.error("STDERR: %s", line)


def _stdout_callback_info(line: str) -> None:
    """Log a Blender stdout line at INFO, demoting known noisy warnings to DEBUG."""
    if any(pattern in line for pattern in _STDOUT_IGNORE_PATTERNS):
        logger.debug("STDOUT: %s", line)
        return
    logger.info("STDOUT: %s", line)


def _run_blender(command: list[str], verbosity_level: int) -> int:
    """Run Blender with the given command and stream output per verbosity."""
    stdout_val, stderr_val = subprocess.PIPE, subprocess.PIPE
    logger.info("Running Blender command: %s", command)
    logger.debug("Raw command: %s", " ".join(command))
    stdout_lines: deque[str] = deque(maxlen=STREAM_TAIL_LINE_LIMIT)
    stderr_lines: deque[str] = deque(maxlen=STREAM_TAIL_LINE_LIMIT)
    with subprocess.Popen(command, stdout=stdout_val, stderr=stderr_val, creationflags=get_process_flags()) as proc:
        stderr_callback_instance = _StderrCallback()
        if verbosity_level == VERBOSITY_ALL:
            stdout_callback = _stdout_callback_info
            stderr_callback = stderr_callback_instance
        elif verbosity_level == VERBOSITY_STDERR:
            stdout_callback = lambda line: logger.debug("STDOUT: %s", line)  # noqa: E731
            stderr_callback = stderr_callback_instance
        else:
            stdout_callback = lambda line: logger.debug("STDOUT: %s", line)  # noqa: E731
            stderr_callback = lambda line: logger.debug("STDERR: %s", line)  # noqa: E731

        stdout_thread = threading.Thread(
            target=_reader_thread,
            args=(proc.stdout, _collecting_callback(stdout_callback, stdout_lines)),
        )
        stderr_thread = threading.Thread(
            target=_reader_thread,
            args=(proc.stderr, _collecting_callback(stderr_callback, stderr_lines)),
        )
        stdout_thread.start()
        stderr_thread.start()
        stdout_thread.join()
        stderr_thread.join()
        returncode = proc.wait()
    if returncode != 0:
        _log_stream_tail("STDOUT", stdout_lines)
        _log_stream_tail("STDERR", stderr_lines)
    return returncode


def _onerror_delete(func: Callable[[str], None], path: str, exc_info: tuple) -> None:
    """Error handler for shutil.rmtree to handle read-only files.

    Args:
        func: The function that raised the exception (e.g., os.remove, os.rmdir).
        path: The file or directory path on which the function failed.
        exc_info: The exception information tuple.
    """
    logger.warning("Failed %s on %s: %s", func.__name__, path, exc_info[1])
    # Example: try to chmod and retry if read-only
    if not os.access(path, os.W_OK):
        try:
            os.chmod(path, stat.S_IWRITE)
            func(path)
        except Exception:
            logger.exception("Retry failed for %s", path)


def _cleanup_paths(datafile: str, temp_folder: str, *, remove_temp_folder: bool) -> None:
    """Remove temporary files/folders created by this module.

    Args:
        datafile: The path to the datafile to remove.
        temp_folder: The path to the temporary folder to remove.
        remove_temp_folder: Flag indicating whether to remove the temp folder.

    Returns:
        None
    """
    try:
        logger.debug("Cleaning up datafile: %s", datafile)
        os.remove(datafile)
    except OSError:
        logger.debug("Failed to remove temp datafile: %s", datafile, exc_info=True)
    if remove_temp_folder:
        try:
            logger.debug("Cleaning up temp folder: %s", temp_folder)
            shutil.rmtree(temp_folder, onerror=_onerror_delete)
        except OSError:
            logger.debug("Failed to remove temp folder: %s", temp_folder, exc_info=True)


@dataclass
class DataPayload:
    """Container for background script input payload."""

    file_path: str
    result_filepath: str
    result_folder: str
    asset_data: dict[str, Any]
    api_key: str
    target_format: str


def send_to_bg(  # noqa: PLR0913
    asset_data: dict[str, Any],
    asset_file_path: str = "",
    template_file_path: str = "",
    temp_folder: str = "",
    result_path: str = "",
    result_folder: str = "",
    api_key: str = "",
    script: str = "",
    addons: str = "",
    binary_type: str = "CLOSEST",
    verbosity_level: int = 2,
    binary_path: str = "",
    target_format: str = "",
) -> int:
    """Run a Blender background script and wait for it to finish.

    Args:
        asset_data: Asset metadata used to select Blender and passed to the script.
        asset_file_path: Asset file to process.
        template_file_path: Optional .blend template to open first.
        temp_folder: Temporary directory used to store the JSON datafile and outputs.
        result_path: Output path used by the background script.
        result_folder: Output directory for multi-file results.
        api_key: API key string forwarded to the background script.
        script: Python file name in paths.BG_SCRIPTS_PATH to run with Blender.
        addons: Comma-separated addon names to enable in Blender.
        binary_type: 'CLOSEST' or 'NEWEST' to select Blender.
        verbosity_level: 0=quiet, 1=stderr only, 2=stdout+stderr streaming.
        binary_path: Explicit Blender binary path to use; if empty, autodetect.
        target_format: Optional target format forwarded to script.

    Returns:
        Process return code from Blender.
    """
    binary_path = _select_binary_path(binary_path, asset_data, asset_file_path=asset_file_path, binary_type=binary_type)

    temp_folder, own_temp_folder = _ensure_temp_folder(temp_folder)
    payload = DataPayload(
        file_path=asset_file_path,
        result_filepath=result_path,
        result_folder=result_folder,
        asset_data=asset_data,
        api_key=api_key,
        target_format=target_format,
    )
    datafile = _write_datafile(temp_folder, payload)
    logger.info("Opening Blender instance to process script: %s", script)
    template_file_path = _resolve_template(template_file_path, asset_file_path)
    command = _build_command(binary_path, template_file_path, script, datafile, addons)
    returncode = _run_blender(command, verbosity_level)

    if returncode != 0:
        logger.error("Error while running command: %s", command)
        logger.error("Return code: %s", returncode)

    # cleanup
    _cleanup_paths(datafile, temp_folder, remove_temp_folder=own_temp_folder)

    return returncode
