"""Generate SEO-friendly alt text for BlenderKit assets using ChatGPT.

Fetch assets with an existing interrogator caption and patch a new parameter
with alt text generated by OpenAI's Chat Completion API.
"""

import os
import tempfile
import time
from typing import Any

import openai

from blenderkit_server_utils import config, log, search, upload, utils

logger = log.create_logger(__name__)

utils.raise_on_missing_env_vars(["BLENDERKIT_API_KEY", "OPENAI_API_KEY", "MAX_ASSET_COUNT"])

PAGE_SIZE_LIMIT: int = 100


# Build the prompt for GPT
def get_gpt_request_text(asset_data: dict[str, Any]) -> str:
    """Build the prompt text for generating an asset image alt text.

    Args:
        asset_data: Asset metadata dictionary with keys like 'assetType',
            'name', 'category', 'dictParameters', and 'description'.

    Returns:
        A prompt string suitable for the Chat Completion API.
    """
    text = f"""We got this information from a BlenderKit 3D {asset_data["assetType"]}.
    name of 3d {asset_data["assetType"]}: "{asset_data["name"]}"
    category slug: "{asset_data["category"]}"
    description AI generated(based on {asset_data["assetType"]} thumbnail, don't trust it too much):
    "{asset_data["dictParameters"]["imageCaptionInterrogator"]}"
    description user written:
    "{asset_data["description"]}"
    software used:
    Blender 3D
    We need a good alt text that optimizes our SEO for google image search, when people search for 3D {asset_data["assetType"]} for Blender 3D.
    Please write an alt text in max 3 sentences, use the keywords in the description and use the better one of the 2 descriptions provided."""  # noqa: E501

    return text


# search for assets to process
def main() -> None:
    """Generate alt texts for assets using GPT-3.5-turbo.

    We search for assets that have interrogator caption, but don't have gpt alt text yet.
    """
    param_name_source: str = "imageCaptionInterrogator"
    param_name_target: str = "imageAltTextGen3"
    params: dict[str, Any] = {
        "order": "-created",
        "asset_type": "model",
        "verification_status": "validated",
        param_name_source + "_isnull": False,
        # just get those which already have interrogator data, but don't have the rest
        param_name_target + "_isnull": True,  # just those that don't have gpt alt caption yet
    }

    dpath: str = tempfile.gettempdir()
    filepath: str = os.path.join(dpath, "assets_for_resolutions.json")
    openai.api_key = config.OPENAI_API_KEY
    if not openai.api_key:
        logger.error("OPENAI_API_KEY is not set; aborting.")
        return

    assets: list[dict[str, Any]] = search.get_search_simple(
        params,
        filepath,
        page_size=min(config.MAX_ASSET_COUNT, PAGE_SIZE_LIMIT),
        max_results=config.MAX_ASSET_COUNT,
        api_key=config.BLENDERKIT_API_KEY,
    )
    if not assets:
        logger.info("No assets found to process.")
        return

    # iterate assets and generate alt text for them
    for asset_data in assets:
        start_time = time.time()

        logger.info("Processing asset %s: %s", asset_data["id"], asset_data["name"])
        request_message = get_gpt_request_text(asset_data)
        # putting everything into try statement since openai api is not very stable, can be overloaded etc.
        try:
            response: Any = openai.ChatCompletion.create(
                model="gpt-3.5-turbo",
                messages=[
                    {"role": "system", "content": "You are a chatbot"},
                    {"role": "user", "content": request_message},
                ],
            )

            result: str = ""
            for choice in response.choices:
                result += choice.message.content
            param_value = result

            # -------------------------------------------------------------------------------------

            upload.patch_individual_parameter(
                asset_id=asset_data["id"],
                param_name=param_name_target,
                param_value=param_value,
                api_key=config.BLENDERKIT_API_KEY,
            )
            upload.get_individual_parameter(
                asset_id=asset_data["id"],
                param_name=param_name_target,
                api_key=config.BLENDERKIT_API_KEY,
            )

            # -------------------------------------------------------------------------------------
            logger.info("Processed in %.3f s", time.time() - start_time)
            # -------------------------------------------------------------------------------------
        except Exception:
            logger.exception("Error processing asset %s", asset_data.get("id"))


if __name__ == "__main__":
    main()
