name: nightly GLTF for Godot

on:
  #schedule:
  #  - cron: '30 5 * * *'
  workflow_dispatch:

env:
  BLENDERKIT_SERVER: 'https://www.blenderkit.com'
  BLENDERKIT_API_KEY: '${{ secrets.BLENDERKIT_API_KEY }}'
  BLENDER_PATH: '/home/headless/blender/blender'
  MAX_ASSET_COUNT: 200

jobs:
  GLTF-Godot:
    runs-on: ubuntu-latest
    container: blenderkit/headless-blender:blender-4.2 # LATEST STABLE
    steps:
      - uses: actions/checkout@v4
      - name: Install lsb-release
        run: apt-get update && apt-get install -y lsb-release python3-pip
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - run: python3 -m pip install -r requirements.txt
      - name: Generate GLTFs for Godot
        run: python3 generate_gltf_godot.py
