name: nightly

on:
  schedule:
    - cron: '30 4 * * *'
  workflow_dispatch:
    inputs:
      BLENDERKIT_SERVER:
        description: 'BLENDERKIT_SERVER'
        required: true
        type: choice
        options:
        - 'https://devel.blenderkit.com'
        - 'https://www.blenderkit.com (DO NOT USE NOW, NEED TO HANDLE API_KEY CHANGING)'

env:
  BLENDERKIT_SERVER: '${{ github.event.inputs.BLENDERKIT_SERVER }}'
  BLENDERKIT_API_KEY: '${{ secrets.BLENDERKIT_API_KEY }}'
  BLENDERS_PATH: ''

jobs:
  Checks:
    runs-on: ubuntu-latest
    container: agajdosi/headless-blender:multi-version
    steps:
      - uses: actions/checkout@v2
      - name: LS
        run: ls -l
      - name: PWD
        run: pwd
      - name: ECHO
        run: echo $BLENDERKIT_SERVER
      - name: ECHO KEY
        run: echo $BLENDERKIT_API_KEY
      - name: IS DEVEL
        run: echo $IS_DEVEL