name: nightly

on:
  schedule:
    - cron: '30 4 * * *'
  push:
    branches: [ main ]
  workflow_dispatch:
    inputs:
      BLENDERKIT_SERVER:
        description: 'BLENDERKIT_SERVER'
        required: true
        type: choice
        options:
        - 'https://devel.blenderkit.com'
        - 'https://www.blenderkit.com (DO NOT USE NOW, NEED TO HANDLE API_KEY CHANGING)'

env:
  BLENDERKIT_SERVER: '${{ github.event.inputs.BLENDERKIT_SERVER }}'
  BLENDERKIT_API_KEY: '${{ secrets.BLENDERKIT_API_KEY }}'
  BLENDERS_PATH: '/home/headless/blenders'
  BLENDERKIT_RESOLUTION_MAX_ASSET_COUNT: 100

jobs:
  Checks:
    runs-on: ubuntu-latest
    container: agajdosi/headless-blender:multi-version
    steps:
      - uses: actions/checkout@v2
      - name: Install pip
        run: sudo apt --fix-broken install pip
      - name: Install requirements
        run: pip3 install -r requirements.txt
      - name: Generate resolutions
        run: python3 generate_resolutions.py
