name: Process Asset

on:
  workflow_dispatch:
    inputs:
      asset_base_id:
        description: 'Asset Base ID'
        required: true
  repository_dispatch:
    types: [process-asset]

env:
  BLENDERKIT_SERVER: 'https://www.blenderkit.com'
  BLENDERKIT_API_KEY: '${{ secrets.BLENDERKIT_API_KEY }}'
  BLENDERS_PATH: '/home/headless/blenders'
  BLENDERKIT_RESOLUTIONS_SEARCH_ID: ${{ github.event.inputs.asset_base_id }}

jobs:
  RESOLUTIONS:
    runs-on: ubuntu-latest
    container: blenderkit/headless-blender:multi-version
    steps:
      - uses: actions/checkout@v2
      - name: Install pip
        run: sudo apt-get install python3-pip -y
      - name: Install requirements
        run: pip install -r requirements.txt
      - name: Generate resolutions
        run: python3 generate_resolutions.py
