name: Test Addon
run-name: Test addon | ${{ github.event.inputs.addon_base_id || github.event.client_payload.addon_base_id }} | ${{ github.event.inputs.verification_status || github.event.client_payload.verification_status }} | ${{ github.event.inputs.is_private || github.event.client_payload.is_private }}

on:
  workflow_dispatch:
    inputs:
      addon_base_id:
        description: 'Addon Base ID'
        required: true
      verification_status:
        description: 'Verification Status of the Asset'
      is_private:
        description: 'Asset Is Private'
        type: boolean
  repository_dispatch:
    types: [test-addon]

env:
  BLENDERKIT_SERVER: 'https://www.blenderkit.com'
  BLENDERKIT_API_KEY: '${{ secrets.BLENDERKIT_API_KEY }}'
  BLENDER_PATH: /home/headless/blender/blender
  ADDON_BASE_ID: ${{ github.event.inputs.addon_base_id || github.event.client_payload.addon_base_id }}

jobs:
  test_matrix:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        version: [4.2, 4.3, 4.4, 4.5]
    container: blenderkit/headless-blender:blender-${{ matrix.version }}
    steps:
      - uses: actions/checkout@v4
      - name: Install lsb-release
        run: apt-get update && apt-get install -y lsb-release python3-pip
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - run: python3 -m pip install -r requirements.txt
      - name: Run TEST script
        run: python3 test_addon.py
      - name: Upload results as artifact
        uses: actions/upload-artifact@v4
        with:
          name: "blender-${{ matrix.version }}"
          path: "temp/test_addon_results.json"

  aggregator:
    name: Collect & Post Combined Results
    needs: test_matrix
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Download all test artifacts
        uses: actions/download-artifact@v4
        with:
          path: results
      - name: list results
        run: tree results
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - run: python3 -m pip install -r requirements.txt
      - name: Report test results
        run: python test_addon_report.py
