name: Test Addon (Multiple Blender Versions)

on:
  workflow_dispatch:

jobs:
  test_matrix:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        version: [4.3, 4.4, 4.5]
    container: blenderkit/headless-blender:blender-${{ matrix.version }}
    steps:
      - uses: actions/checkout@v4
      - name: Install dependencies
        run: |
          apt-get update && apt-get install -y python3-pip
          pip install -r requirements.txt
      - name: Run test script and generate results
        run: python test_addon.py
      - name: Upload results as artifact
        uses: actions/upload-artifact@v3
        with:
          name: "results-${{ matrix.version }}"
          path: "temp/test_addon_results.json"

  # 3) Aggregator job
  aggregator:
    name: Collect & Post Combined Results
    needs: test_matrix
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Download all test artifacts
        uses: actions/download-artifact@v3
        with:
          path: results
      - name: Install Python dependencies
        run: pip install requests
      - name: Tree files
        run: tree results
