name: Test Addon
run-name: Test addon | ${{ github.event.inputs.addon_base_id || github.event.client_payload.addon_base_id }} | ${{ github.event.inputs.verification_status || github.event.client_payload.verification_status }} | ${{ github.event.inputs.is_private || github.event.client_payload.is_private }}

on:
  workflow_dispatch:
    inputs:
      addon_base_id:
        description: 'Addon Base ID'
        required: true
      verification_status:
        description: 'Verification Status of the Asset'
      is_private:
        description: 'Asset Is Private'
        type: boolean
  repository_dispatch:
    types: [test-addon]

env:
  BLENDERKIT_SERVER: 'https://www.blenderkit.com'
  BLENDERKIT_API_KEY: '${{ secrets.BLENDERKIT_API_KEY }}'
  BLENDER_PATH: /home/headless/blender/blender
  ADDON_BASE_ID: ${{ github.event.inputs.addon_base_id || github.event.client_payload.addon_base_id }}

jobs:
  RESULTS:
    name: Collect & Post Results
    runs-on: ubuntu-latest
    needs: 
      - TEST_ADDON_B43
      - TEST_ADDON_B44
      - TEST_ADDON_B45
    steps:
      - name: Print raw JSON from each job
        run: |
          echo "B43: ${{ needs.TEST_ADDON_B43.outputs.test_results }}"
          echo "B44: ${{ needs.TEST_ADDON_B44.outputs.test_results }}"
          echo "B45: ${{ needs.TEST_ADDON_B45.outputs.test_results }}"

  TEST_ADDON_B43:
    name: Addon -> smoke test Blender 4.3
    runs-on: ubuntu-latest
    container: blenderkit/headless-blender:blender-4.3
    outputs:
      test_results: ${{ steps.test_addon.outputs.test_results }}
    steps:
      - uses: actions/checkout@v4
      - name: Install lsb-release
        run: apt-get update && apt-get install -y lsb-release python3-pip
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - run: python3 -m pip install -r requirements.txt
      - name: Test Add-on
        id: test_addon
        run: python3 test_addon.py >> $GITHUB_OUTPUT

  TEST_ADDON_B44:
    name: Addon -> smoke test Blender 4.4
    runs-on: ubuntu-latest
    container: blenderkit/headless-blender:blender-4.4
    outputs:
      test_results: ${{ steps.test_addon.outputs.test_results }}
    steps:
      - uses: actions/checkout@v4
      - name: Install lsb-release
        run: apt-get update && apt-get install -y lsb-release python3-pip
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - run: python3 -m pip install -r requirements.txt
      - name: Test Add-on
        id: test_addon
        run: python3 test_addon.py >> $GITHUB_OUTPUT

  TEST_ADDON_B45:
    name: Addon -> smoke test Blender 4.5
    runs-on: ubuntu-latest
    container: blenderkit/headless-blender:blender-4.5
    outputs:
      test_results: ${{ steps.test_addon.outputs.test_results }}
    steps:
      - uses: actions/checkout@v4
      - name: Install lsb-release
        run: apt-get update && apt-get install -y lsb-release python3-pip
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - run: python3 -m pip install -r requirements.txt
      - name: Test Add-on
        id: test_addon
        run: python3 test_addon.py >> $GITHUB_OUTPUT
